# Flujo de trabajo simple para desplegar contenido estático en GitHub Pages
name: Desplegar contenido estático en Pages

on:
  # Se ejecuta cuando se hace push a la rama principal
  push:
    branches: ['main']

  # Permite ejecutar este flujo de trabajo manualmente desde la pestaña de Acciones
  workflow_dispatch:

# Establece los permisos del GITHUB_TOKEN para permitir el despliegue en GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Permite un solo despliegue concurrente
concurrency:
  group: 'pages'
  cancel-in-progress: true

jobs:
  # Trabajo único de despliegue ya que solo estamos desplegando
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '18.x'
          cache: 'npm'
          
      - name: Install dependencies
        run: npm ci
        
      - name: Build
        run: npm run build
        env:
          NODE_ENV: production
          
      - name: Create .nojekyll file
        run: touch ./dist/.nojekyll
        
      - name: Setup Pages
        uses: actions/configure-pages@v5
        
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          # Upload the dist folder
          path: './dist'
          
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
